name: Update

on:
  workflow_dispatch:
    inputs:
      foo:
        description: 'foo'
        required: true
      hi:
        description: 'hi'
        required: true

defaults:
  run:
    shell: bash

jobs:

  update:
    runs-on: ubuntu-latest

    steps:
      - name: check-123
        run: |
          echo ${{ inputs.foo }}
          echo ${{ inputs.hi }}
